package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1



/**
 * CareerCourse generated by hbm2java
 */
public class CareerCourseDTO  implements java.io.Serializable {


     private Integer id;
     private CareerDTO career;
     private CourseDTO course;
     private int plan;
     private String pensumYear;
     private String pensumSemester;
     private Boolean state;

    public CareerCourseDTO() {
    }

	
    public CareerCourseDTO(CareerDTO career, CourseDTO course, int plan) {
        this.career = career;
        this.course = course;
        this.plan = plan;
    }
    public CareerCourseDTO(CareerDTO career, CourseDTO course, int plan, String pensumYear, String pensumSemester, Boolean state) {
       this.career = career;
       this.course = course;
       this.plan = plan;
       this.pensumYear = pensumYear;
       this.pensumSemester = pensumSemester;
       this.state = state;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CareerDTO getCareer() {
        return this.career;
    }
    
    public void setCareer(CareerDTO career) {
        this.career = career;
    }
    public CourseDTO getCourse() {
        return this.course;
    }
    
    public void setCourse(CourseDTO course) {
        this.course = course;
    }
    public int getPlan() {
        return this.plan;
    }
    
    public void setPlan(int plan) {
        this.plan = plan;
    }
    public String getPensumYear() {
        return this.pensumYear;
    }
    
    public void setPensumYear(String pensumYear) {
        this.pensumYear = pensumYear;
    }
    public String getPensumSemester() {
        return this.pensumSemester;
    }
    
    public void setPensumSemester(String pensumSemester) {
        this.pensumSemester = pensumSemester;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }




}


