package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Career generated by hbm2java
 */
public class CareerDTO  implements java.io.Serializable {


     private Integer id;
     private CareerTypeDTO careerType;
     private FacultyDTO faculty;
     private String name;
     private Boolean state;
     private Set<CareerCourseDTO> careerCourses = new HashSet<CareerCourseDTO>(0);
     private Set<CareerStudentDTO> careerStudents = new HashSet<CareerStudentDTO>(0);

    public CareerDTO() {
    }

	
    public CareerDTO(CareerTypeDTO careerType, FacultyDTO faculty, String name) {
        this.careerType = careerType;
        this.faculty = faculty;
        this.name = name;
    }
    public CareerDTO(CareerTypeDTO careerType, FacultyDTO faculty, String name, Boolean state, Set<CareerCourseDTO> careerCourses, Set<CareerStudentDTO> careerStudents) {
       this.careerType = careerType;
       this.faculty = faculty;
       this.name = name;
       this.state = state;
       this.careerCourses = careerCourses;
       this.careerStudents = careerStudents;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CareerTypeDTO getCareerType() {
        return this.careerType;
    }
    
    public void setCareerType(CareerTypeDTO careerType) {
        this.careerType = careerType;
    }
    public FacultyDTO getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(FacultyDTO faculty) {
        this.faculty = faculty;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }
    public Set<CareerCourseDTO> getCareerCourses() {
        return this.careerCourses;
    }
    
    public void setCareerCourses(Set<CareerCourseDTO> careerCourses) {
        this.careerCourses = careerCourses;
    }
    public Set<CareerStudentDTO> getCareerStudents() {
        return this.careerStudents;
    }
    
    public void setCareerStudents(Set<CareerStudentDTO> careerStudents) {
        this.careerStudents = careerStudents;
    }




}


