package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CareerType generated by hbm2java
 */
public class CareerTypeDTO  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Boolean state;
     private Set<CareerDTO> careers = new HashSet<CareerDTO>(0);

    public CareerTypeDTO() {
    }

	
    public CareerTypeDTO(String name) {
        this.name = name;
    }
    public CareerTypeDTO(String name, Boolean state, Set<CareerDTO> careers) {
       this.name = name;
       this.state = state;
       this.careers = careers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }
    public Set<CareerDTO> getCareers() {
        return this.careers;
    }
    
    public void setCareers(Set<CareerDTO> careers) {
        this.careers = careers;
    }




}


