package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1



/**
 * CareerStudent generated by hbm2java
 */
public class CareerStudentDTO  implements java.io.Serializable {


     private Integer id;
     private CareerDTO career;
     private StudentDTO student;
     private int incomeYear;
     private Boolean state;

    public CareerStudentDTO() {
    }

	
    public CareerStudentDTO(CareerDTO career, StudentDTO student, int incomeYear) {
        this.career = career;
        this.student = student;
        this.incomeYear = incomeYear;
    }
    public CareerStudentDTO(CareerDTO career, StudentDTO student, int incomeYear, Boolean state) {
       this.career = career;
       this.student = student;
       this.incomeYear = incomeYear;
       this.state = state;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CareerDTO getCareer() {
        return this.career;
    }
    
    public void setCareer(CareerDTO career) {
        this.career = career;
    }
    public StudentDTO getStudent() {
        return this.student;
    }
    
    public void setStudent(StudentDTO student) {
        this.student = student;
    }
    public int getIncomeYear() {
        return this.incomeYear;
    }
    
    public void setIncomeYear(int incomeYear) {
        this.incomeYear = incomeYear;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }




}


