package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1



/**
 * Correction generated by hbm2java
 */
public class CorrectionDTO  implements java.io.Serializable {


     private Integer id;
     private GradeDTO grade;
     private String description;
     private String filePath;
     private String correctionState;
     private Boolean state;

    public CorrectionDTO() {
    }

	
    public CorrectionDTO(GradeDTO grade, String description, String correctionState) {
        this.grade = grade;
        this.description = description;
        this.correctionState = correctionState;
    }
    public CorrectionDTO(GradeDTO grade, String description, String filePath, String correctionState, Boolean state) {
       this.grade = grade;
       this.description = description;
       this.filePath = filePath;
       this.correctionState = correctionState;
       this.state = state;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public GradeDTO getGrade() {
        return this.grade;
    }
    
    public void setGrade(GradeDTO grade) {
        this.grade = grade;
    }
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }
    public String getCorrectionState() {
        return this.correctionState;
    }
    
    public void setCorrectionState(String correctionState) {
        this.correctionState = correctionState;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }




}


