package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Course generated by hbm2java
 */
public class CourseDTO  implements java.io.Serializable {


     private Integer id;
     private CourseDTO course;
     private FacultyDTO faculty;
     private String name;
     private String courseCode;
     private String semester;
     private Boolean inter;
     private Boolean laboratory;
     private int uv;
     private Boolean state;
     private Set<EvaluationDTO> evaluations = new HashSet<EvaluationDTO>(0);
     private Set<CareerCourseDTO> careerCourses = new HashSet<CareerCourseDTO>(0);
     private Set<CourseDTO> courses = new HashSet<CourseDTO>(0);
     private Set<CourseTeacherDTO> courseTeachers = new HashSet<CourseTeacherDTO>(0);

    public CourseDTO() {
    }

	
    public CourseDTO(String name, String courseCode, String semester, int uv) {
        this.name = name;
        this.courseCode = courseCode;
        this.semester = semester;
        this.uv = uv;
    }
    public CourseDTO(CourseDTO course, FacultyDTO faculty, String name, String courseCode, String semester, Boolean inter, Boolean laboratory, int uv, Boolean state, Set<EvaluationDTO> evaluations, Set<CareerCourseDTO> careerCourses, Set<CourseDTO> courses, Set<CourseTeacherDTO> courseTeachers) {
       this.course = course;
       this.faculty = faculty;
       this.name = name;
       this.courseCode = courseCode;
       this.semester = semester;
       this.inter = inter;
       this.laboratory = laboratory;
       this.uv = uv;
       this.state = state;
       this.evaluations = evaluations;
       this.careerCourses = careerCourses;
       this.courses = courses;
       this.courseTeachers = courseTeachers;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CourseDTO getCourse() {
        return this.course;
    }
    
    public void setCourse(CourseDTO course) {
        this.course = course;
    }
    public FacultyDTO getFaculty() {
        return this.faculty;
    }
    
    public void setFaculty(FacultyDTO faculty) {
        this.faculty = faculty;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getCourseCode() {
        return this.courseCode;
    }
    
    public void setCourseCode(String courseCode) {
        this.courseCode = courseCode;
    }
    public String getSemester() {
        return this.semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }
    public Boolean getInter() {
        return this.inter;
    }
    
    public void setInter(Boolean inter) {
        this.inter = inter;
    }
    public Boolean getLaboratory() {
        return this.laboratory;
    }
    
    public void setLaboratory(Boolean laboratory) {
        this.laboratory = laboratory;
    }
    public int getUv() {
        return this.uv;
    }
    
    public void setUv(int uv) {
        this.uv = uv;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }
    public Set<EvaluationDTO> getEvaluations() {
        return this.evaluations;
    }
    
    public void setEvaluations(Set<EvaluationDTO> evaluations) {
        this.evaluations = evaluations;
    }
    public Set<CareerCourseDTO> getCareerCourses() {
        return this.careerCourses;
    }
    
    public void setCareerCourses(Set<CareerCourseDTO> careerCourses) {
        this.careerCourses = careerCourses;
    }
    public Set<CourseDTO> getCourses() {
        return this.courses;
    }
    
    public void setCourses(Set<CourseDTO> courses) {
        this.courses = courses;
    }
    public Set<CourseTeacherDTO> getCourseTeachers() {
        return this.courseTeachers;
    }
    
    public void setCourseTeachers(Set<CourseTeacherDTO> courseTeachers) {
        this.courseTeachers = courseTeachers;
    }




}


