package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CourseTeacher generated by hbm2java
 */
public class CourseTeacherDTO  implements java.io.Serializable {


     private Integer id;
     private CourseDTO course;
     private EmployeeDTO employee;
     private int courseYear;
     private String semester;
     private int classCount;
     private Boolean state;
     private Set<RegisteredCourseDTO> registeredCourses = new HashSet<RegisteredCourseDTO>(0);

    public CourseTeacherDTO() {
    }

	
    public CourseTeacherDTO(CourseDTO course, EmployeeDTO employee, int courseYear, String semester, int classCount) {
        this.course = course;
        this.employee = employee;
        this.courseYear = courseYear;
        this.semester = semester;
        this.classCount = classCount;
    }
    public CourseTeacherDTO(CourseDTO course, EmployeeDTO employee, int courseYear, String semester, int classCount, Boolean state, Set<RegisteredCourseDTO> registeredCourses) {
       this.course = course;
       this.employee = employee;
       this.courseYear = courseYear;
       this.semester = semester;
       this.classCount = classCount;
       this.state = state;
       this.registeredCourses = registeredCourses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CourseDTO getCourse() {
        return this.course;
    }
    
    public void setCourse(CourseDTO course) {
        this.course = course;
    }
    public EmployeeDTO getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(EmployeeDTO employee) {
        this.employee = employee;
    }
    public int getCourseYear() {
        return this.courseYear;
    }
    
    public void setCourseYear(int courseYear) {
        this.courseYear = courseYear;
    }
    public String getSemester() {
        return this.semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }
    public int getClassCount() {
        return this.classCount;
    }
    
    public void setClassCount(int classCount) {
        this.classCount = classCount;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }
    public Set<RegisteredCourseDTO> getRegisteredCourses() {
        return this.registeredCourses;
    }
    
    public void setRegisteredCourses(Set<RegisteredCourseDTO> registeredCourses) {
        this.registeredCourses = registeredCourses;
    }




}


