package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Grade generated by hbm2java
 */
public class GradeDTO  implements java.io.Serializable {


     private Integer id;
     private EvaluationDTO evaluation;
     private RegisteredCourseDTO registeredCourse;
     private float grade;
     private String observations;
     private Boolean state;
     private Set<CorrectionDTO> corrections = new HashSet<CorrectionDTO>(0);

    public GradeDTO() {
    }

	
    public GradeDTO(EvaluationDTO evaluation, RegisteredCourseDTO registeredCourse, float grade) {
        this.evaluation = evaluation;
        this.registeredCourse = registeredCourse;
        this.grade = grade;
    }
    public GradeDTO(EvaluationDTO evaluation, RegisteredCourseDTO registeredCourse, float grade, String observations, Boolean state, Set<CorrectionDTO> corrections) {
       this.evaluation = evaluation;
       this.registeredCourse = registeredCourse;
       this.grade = grade;
       this.observations = observations;
       this.state = state;
       this.corrections = corrections;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public EvaluationDTO getEvaluation() {
        return this.evaluation;
    }
    
    public void setEvaluation(EvaluationDTO evaluation) {
        this.evaluation = evaluation;
    }
    public RegisteredCourseDTO getRegisteredCourse() {
        return this.registeredCourse;
    }
    
    public void setRegisteredCourse(RegisteredCourseDTO registeredCourse) {
        this.registeredCourse = registeredCourse;
    }
    public float getGrade() {
        return this.grade;
    }
    
    public void setGrade(float grade) {
        this.grade = grade;
    }
    public String getObservations() {
        return this.observations;
    }
    
    public void setObservations(String observations) {
        this.observations = observations;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }
    public Set<CorrectionDTO> getCorrections() {
        return this.corrections;
    }
    
    public void setCorrections(Set<CorrectionDTO> corrections) {
        this.corrections = corrections;
    }




}


