package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Entity;

/**
 * Person generated by hbm2java
 */
public class PersonDTO  implements java.io.Serializable {


     private Integer id;
     private String name;
     private String surname;
     private String phone;
     private String email;
     private String dui;
     private String address;
     private Boolean state;
     private Set<UserDTO> users = new HashSet<UserDTO>(0);

    public PersonDTO() {
    }

	
    public PersonDTO(String name, String surname, String phone, String email, String dui, String address) {
        this.name = name;
        this.surname = surname;
        this.phone = phone;
        this.email = email;
        this.dui = dui;
        this.address = address;
    }
    public PersonDTO(String name, String surname, String phone, String email, String dui, String address, Boolean state, Set<UserDTO> users) {
       this.name = name;
       this.surname = surname;
       this.phone = phone;
       this.email = email;
       this.dui = dui;
       this.address = address;
       this.state = state;
       this.users = users;
    }
    
    public PersonDTO(int id, String name, String surname, String phone, String email, String dui, String address, Boolean state) {
       this.id = id;
       this.name = name;
       this.surname = surname;
       this.phone = phone;
       this.email = email;
       this.dui = dui;
       this.address = address;
       this.state = state;
    }
    public PersonDTO(int id, String name, String surname, String phone, String email, String dui, String address, Boolean state, HashSet<UserDTO> users) {
       this.id = id;
        this.name = name;
       this.surname = surname;
       this.phone = phone;
       this.email = email;
       this.dui = dui;
       this.address = address;
       this.state = state;
       this.users = users;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getSurname() {
        return this.surname;
    }
    
    public void setSurname(String surname) {
        this.surname = surname;
    }
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getDui() {
        return this.dui;
    }
    
    public void setDui(String dui) {
        this.dui = dui;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }
    public Set<UserDTO> getUsers() {
        return this.users;
    }
    
    public void setUsers(Set<UserDTO> users) {
        this.users = users;
    }




}


