package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RegisteredCourse generated by hbm2java
 */
public class RegisteredCourseDTO  implements java.io.Serializable {


     private Integer id;
     private CourseTeacherDTO courseTeacher;
     private StudentDTO student;
     private String courseState;
     private Boolean state;
     private Set<GradeDTO> grades = new HashSet<GradeDTO>(0);
     private Set<UnattendanceDTO> unattendances = new HashSet<UnattendanceDTO>(0);

    public RegisteredCourseDTO() {
    }

	
    public RegisteredCourseDTO(CourseTeacherDTO courseTeacher, StudentDTO student) {
        this.courseTeacher = courseTeacher;
        this.student = student;
    }
    public RegisteredCourseDTO(CourseTeacherDTO courseTeacher, StudentDTO student, String courseState, Boolean state, Set<GradeDTO> grades, Set<UnattendanceDTO> unattendances) {
       this.courseTeacher = courseTeacher;
       this.student = student;
       this.courseState = courseState;
       this.state = state;
       this.grades = grades;
       this.unattendances = unattendances;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CourseTeacherDTO getCourseTeacher() {
        return this.courseTeacher;
    }
    
    public void setCourseTeacher(CourseTeacherDTO courseTeacher) {
        this.courseTeacher = courseTeacher;
    }
    public StudentDTO getStudent() {
        return this.student;
    }
    
    public void setStudent(StudentDTO student) {
        this.student = student;
    }
    public String getCourseState() {
        return this.courseState;
    }
    
    public void setCourseState(String courseState) {
        this.courseState = courseState;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }
    public Set<GradeDTO> getGrades() {
        return this.grades;
    }
    
    public void setGrades(Set<GradeDTO> grades) {
        this.grades = grades;
    }
    public Set<UnattendanceDTO> getUnattendances() {
        return this.unattendances;
    }
    
    public void setUnattendances(Set<UnattendanceDTO> unattendances) {
        this.unattendances = unattendances;
    }




}


