package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Role generated by hbm2java
 */
public class RoleDTO  implements java.io.Serializable {


     private Integer id;
     private String role;
     private Boolean teach;
     private Boolean manageUsers;
     private Boolean manageStudents;
     private Boolean manageEmployees;
     private Boolean manageFaculties;
     private Boolean manageCareers;
     private Boolean manageCourses;
     private Boolean managePensums;
     private Boolean manageEvaluations;
     private Boolean manageRoles;
     private Boolean state;
     private Set<EmployeeDTO> employees = new HashSet<EmployeeDTO>(0);

    public RoleDTO() {
    }

	
    public RoleDTO(String role) {
        this.role = role;
    }
    public RoleDTO(String role, Boolean teach, Boolean manageUsers, Boolean manageStudents, Boolean manageEmployees, Boolean manageFaculties, Boolean manageCareers, Boolean manageCourses, Boolean managePensums, Boolean manageEvaluations, Boolean manageRoles, Boolean state, Set<EmployeeDTO> employees) {
       this.role = role;
       this.teach = teach;
       this.manageUsers = manageUsers;
       this.manageStudents = manageStudents;
       this.manageEmployees = manageEmployees;
       this.manageFaculties = manageFaculties;
       this.manageCareers = manageCareers;
       this.manageCourses = manageCourses;
       this.managePensums = managePensums;
       this.manageEvaluations = manageEvaluations;
       this.manageRoles = manageRoles;
       this.state = state;
       this.employees = employees;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }
    public Boolean getTeach() {
        return this.teach;
    }
    
    public void setTeach(Boolean teach) {
        this.teach = teach;
    }
    public Boolean getManageUsers() {
        return this.manageUsers;
    }
    
    public void setManageUsers(Boolean manageUsers) {
        this.manageUsers = manageUsers;
    }
    public Boolean getManageStudents() {
        return this.manageStudents;
    }
    
    public void setManageStudents(Boolean manageStudents) {
        this.manageStudents = manageStudents;
    }
    public Boolean getManageEmployees() {
        return this.manageEmployees;
    }
    
    public void setManageEmployees(Boolean manageEmployees) {
        this.manageEmployees = manageEmployees;
    }
    public Boolean getManageFaculties() {
        return this.manageFaculties;
    }
    
    public void setManageFaculties(Boolean manageFaculties) {
        this.manageFaculties = manageFaculties;
    }
    public Boolean getManageCareers() {
        return this.manageCareers;
    }
    
    public void setManageCareers(Boolean manageCareers) {
        this.manageCareers = manageCareers;
    }
    public Boolean getManageCourses() {
        return this.manageCourses;
    }
    
    public void setManageCourses(Boolean manageCourses) {
        this.manageCourses = manageCourses;
    }
    public Boolean getManagePensums() {
        return this.managePensums;
    }
    
    public void setManagePensums(Boolean managePensums) {
        this.managePensums = managePensums;
    }
    public Boolean getManageEvaluations() {
        return this.manageEvaluations;
    }
    
    public void setManageEvaluations(Boolean manageEvaluations) {
        this.manageEvaluations = manageEvaluations;
    }
    public Boolean getManageRoles() {
        return this.manageRoles;
    }
    
    public void setManageRoles(Boolean manageRoles) {
        this.manageRoles = manageRoles;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }
    public Set<EmployeeDTO> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<EmployeeDTO> employees) {
        this.employees = employees;
    }




}


