package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Student generated by hbm2java
 */
public class StudentDTO  implements java.io.Serializable {


     private Integer id;
     private UserDTO user;
     private Boolean state;
     private Set<CareerStudentDTO> careerStudents = new HashSet<CareerStudentDTO>(0);
     private Set<RegisteredCourseDTO> registeredCourses = new HashSet<RegisteredCourseDTO>(0);

    public StudentDTO() {
    }

	
    public StudentDTO(UserDTO user) {
        this.user = user;
    }
    public StudentDTO(UserDTO user, Boolean state, Set<CareerStudentDTO> careerStudents, Set<RegisteredCourseDTO> registeredCourses) {
       this.user = user;
       this.state = state;
       this.careerStudents = careerStudents;
       this.registeredCourses = registeredCourses;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public UserDTO getUser() {
        return this.user;
    }
    
    public void setUser(UserDTO user) {
        this.user = user;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }
    public Set<CareerStudentDTO> getCareerStudents() {
        return this.careerStudents;
    }
    
    public void setCareerStudents(Set<CareerStudentDTO> careerStudents) {
        this.careerStudents = careerStudents;
    }
    public Set<RegisteredCourseDTO> getRegisteredCourses() {
        return this.registeredCourses;
    }
    
    public void setRegisteredCourses(Set<RegisteredCourseDTO> registeredCourses) {
        this.registeredCourses = registeredCourses;
    }




}


