package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Unattendance generated by hbm2java
 */
public class UnattendanceDTO  implements java.io.Serializable {


     private Integer id;
     private RegisteredCourseDTO registeredCourse;
     private Date unattendanceDate;
     private Boolean state;

    public UnattendanceDTO() {
    }

	
    public UnattendanceDTO(RegisteredCourseDTO registeredCourse) {
        this.registeredCourse = registeredCourse;
    }
    public UnattendanceDTO(RegisteredCourseDTO registeredCourse, Date unattendanceDate, Boolean state) {
       this.registeredCourse = registeredCourse;
       this.unattendanceDate = unattendanceDate;
       this.state = state;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public RegisteredCourseDTO getRegisteredCourse() {
        return this.registeredCourse;
    }
    
    public void setRegisteredCourse(RegisteredCourseDTO registeredCourse) {
        this.registeredCourse = registeredCourse;
    }
    public Date getUnattendanceDate() {
        return this.unattendanceDate;
    }
    
    public void setUnattendanceDate(Date unattendanceDate) {
        this.unattendanceDate = unattendanceDate;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }




}


