package dtoaaaaaa;
// Generated 10-06-2018 08:41:00 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class UserDTO  implements java.io.Serializable {


     private Integer id;
     private PersonDTO person;
     private String username;
     private String pass;
     private String imagePath;
     private Boolean state;
     private Set<StudentDTO> students = new HashSet<StudentDTO>(0);
     private Set<EmployeeDTO> employees = new HashSet<EmployeeDTO>(0);

    public UserDTO() {
    }

	
    public UserDTO(PersonDTO person, String username, String pass, String imagePath) {
        this.person = person;
        this.username = username;
        this.pass = pass;
        this.imagePath = imagePath;
    }
    public UserDTO(PersonDTO person, String username, String pass, String imagePath, Boolean state, Set<StudentDTO> students, Set<EmployeeDTO> employees) {
       this.person = person;
       this.username = username;
       this.pass = pass;
       this.imagePath = imagePath;
       this.state = state;
       this.students = students;
       this.employees = employees;
    }
    public UserDTO(int id, PersonDTO person, String username, String pass, String imagePath, Boolean state, Set<StudentDTO> students, Set<EmployeeDTO> employees) {
       this.id = id;
        this.person = person;
       this.username = username;
       this.pass = pass;
       this.imagePath = imagePath;
       this.state = state;
       this.students = students;
       this.employees = employees;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public PersonDTO getPerson() {
        return this.person;
    }
    
    public void setPerson(PersonDTO person) {
        this.person = person;
    }
    public String getUsername() {
        return this.username;
    }
    
    public void setUsername(String username) {
        this.username = username;
    }
    public String getPass() {
        return this.pass;
    }
    
    public void setPass(String pass) {
        this.pass = pass;
    }
    public String getImagePath() {
        return this.imagePath;
    }
    
    public void setImagePath(String imagePath) {
        this.imagePath = imagePath;
    }
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }
    public Set<StudentDTO> getStudents() {
        return this.students;
    }
    
    public void setStudents(Set<StudentDTO> students) {
        this.students = students;
    }
    public Set<EmployeeDTO> getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set<EmployeeDTO> employees) {
        this.employees = employees;
    }




}


