package hibernate;
// Generated 10-06-2018 09:26:51 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonManagedReference;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * CareerStudent generated by hbm2java
 */
@Entity
@Table(name="career_student"
    ,catalog="gradecheck"
)
public class CareerStudent  implements java.io.Serializable {


     private Integer id;
     @JsonManagedReference
     private Career career;
     @JsonManagedReference
     private Student student;
     private int incomeYear;
     private String careerState;
     private Boolean state;

    public CareerStudent() {
    }

	
    public CareerStudent(Career career, Student student, int incomeYear) {
        this.career = career;
        this.student = student;
        this.incomeYear = incomeYear;
    }
    public CareerStudent(Career career, Student student, int incomeYear, String careerState, Boolean state) {
       this.career = career;
       this.student = student;
       this.incomeYear = incomeYear;
       this.state = state;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="career_id", nullable=false)
    public Career getCareer() {
        return this.career;
    }
    
    public void setCareer(Career career) {
        this.career = career;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="income_year", nullable=false)
    public int getIncomeYear() {
        return this.incomeYear;
    }
    
    public void setIncomeYear(int incomeYear) {
        this.incomeYear = incomeYear;
    }

    @Column(name="career_state", length=10, nullable=false)
    public String getCareerState() {
        return this.careerState;
    }
    
    public void setCareerState(String careerState) {
        this.careerState = careerState;
    }
    
    @Column(name="state")
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }




}


