package hibernate;
// Generated 10-06-2018 09:26:51 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonManagedReference;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Correction generated by hbm2java
 */
@Entity
@XmlRootElement (name = "correction")
@Table(name="correction"
    ,catalog="gradecheck"
)
public class Correction  implements java.io.Serializable {


     private Integer id;
     @JsonManagedReference
     private Grade grade;
     private String description;
     private String filePath;
     private String correctionState;
     private Boolean state;

    public Correction() {
    }

	
    public Correction(Grade grade, String description, String correctionState) {
        this.grade = grade;
        this.description = description;
        this.correctionState = correctionState;
    }
    public Correction(Grade grade, String description, String filePath, String correctionState, Boolean state) {
       this.grade = grade;
       this.description = description;
       this.filePath = filePath;
       this.correctionState = correctionState;
       this.state = state;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="grade_id", nullable=false)
    public Grade getGrade() {
        return this.grade;
    }
    
    public void setGrade(Grade grade) {
        this.grade = grade;
    }

    
    @Column(name="description", nullable=false, length=1000)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="file_path", length=1000)
    public String getFilePath() {
        return this.filePath;
    }
    
    public void setFilePath(String filePath) {
        this.filePath = filePath;
    }

    
    @Column(name="correction_state", nullable=false, length=10)
    public String getCorrectionState() {
        return this.correctionState;
    }
    
    public void setCorrectionState(String correctionState) {
        this.correctionState = correctionState;
    }

    
    @Column(name="state")
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }




}


