package hibernate;
// Generated 10-06-2018 09:26:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * CourseTeacher generated by hbm2java
 */
@Entity
@Table(name="course_teacher"
    ,catalog="gradecheck"
)
public class CourseTeacher  implements java.io.Serializable {


     private Integer id;
     private Course course;
     private Employee employee;
     private int courseYear;
     private String semester;
     private int classCount;
     private Boolean state;
     private Set registeredCourses = new HashSet(0);

    public CourseTeacher() {
    }

	
    public CourseTeacher(Course course, Employee employee, int courseYear, String semester, int classCount) {
        this.course = course;
        this.employee = employee;
        this.courseYear = courseYear;
        this.semester = semester;
        this.classCount = classCount;
    }
    public CourseTeacher(Course course, Employee employee, int courseYear, String semester, int classCount, Boolean state, Set registeredCourses) {
       this.course = course;
       this.employee = employee;
       this.courseYear = courseYear;
       this.semester = semester;
       this.classCount = classCount;
       this.state = state;
       this.registeredCourses = registeredCourses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_id", nullable=false)
    public Course getCourse() {
        return this.course;
    }
    
    public void setCourse(Course course) {
        this.course = course;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="employee_id", nullable=false)
    public Employee getEmployee() {
        return this.employee;
    }
    
    public void setEmployee(Employee employee) {
        this.employee = employee;
    }

    
    @Column(name="course_year", nullable=false)
    public int getCourseYear() {
        return this.courseYear;
    }
    
    public void setCourseYear(int courseYear) {
        this.courseYear = courseYear;
    }

    
    @Column(name="semester", nullable=false, length=10)
    public String getSemester() {
        return this.semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }

    
    @Column(name="class_count", nullable=false)
    public int getClassCount() {
        return this.classCount;
    }
    
    public void setClassCount(int classCount) {
        this.classCount = classCount;
    }

    
    @Column(name="state")
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="courseTeacher")
    public Set getRegisteredCourses() {
        return this.registeredCourses;
    }
    
    public void setRegisteredCourses(Set registeredCourses) {
        this.registeredCourses = registeredCourses;
    }




}


