package hibernate;
// Generated 10-06-2018 09:26:51 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * Employee generated by hbm2java
 */
@Entity
@XmlRootElement( name = "employee")
@XmlSeeAlso ({CourseTeacher.class})
@Table(name="employee"
    ,catalog="gradecheck"
)
public class Employee  implements java.io.Serializable {


     private Integer id;
     @JsonManagedReference
     private Role role;
     @JsonManagedReference
     private User user;
     private Boolean state;
     @JsonBackReference
     private Set courseTeachers = new HashSet(0);

    public Employee() {
    }

	
    public Employee(Role role, User user) {
        this.role = role;
        this.user = user;
    }
    public Employee(Role role, User user, Boolean state, Set courseTeachers) {
       this.role = role;
       this.user = user;
       this.state = state;
       this.courseTeachers = courseTeachers;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="role_id", nullable=false)
    public Role getRole() {
        return this.role;
    }
    
    public void setRole(Role role) {
        this.role = role;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="state")
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="employee")
    public Set getCourseTeachers() {
        return this.courseTeachers;
    }
    
    public void setCourseTeachers(Set courseTeachers) {
        this.courseTeachers = courseTeachers;
    }




}


