package hibernate;
// Generated 10-06-2018 09:26:51 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * RegisteredCourse generated by hbm2java
 */
@Entity
@Table(name="registered_course"
    ,catalog="gradecheck"
)
public class RegisteredCourse  implements java.io.Serializable {


     private Integer id;
     private CourseTeacher courseTeacher;
     private Student student;
     private String courseState;
     private Boolean state;
     private Set grades = new HashSet(0);
     private Set unattendances = new HashSet(0);

    public RegisteredCourse() {
    }

	
    public RegisteredCourse(CourseTeacher courseTeacher, Student student) {
        this.courseTeacher = courseTeacher;
        this.student = student;
    }
    public RegisteredCourse(CourseTeacher courseTeacher, Student student, String courseState, Boolean state, Set grades, Set unattendances) {
       this.courseTeacher = courseTeacher;
       this.student = student;
       this.courseState = courseState;
       this.state = state;
       this.grades = grades;
       this.unattendances = unattendances;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="course_teacher_id", nullable=false)
    public CourseTeacher getCourseTeacher() {
        return this.courseTeacher;
    }
    
    public void setCourseTeacher(CourseTeacher courseTeacher) {
        this.courseTeacher = courseTeacher;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="student_id", nullable=false)
    public Student getStudent() {
        return this.student;
    }
    
    public void setStudent(Student student) {
        this.student = student;
    }

    
    @Column(name="course_state", length=9)
    public String getCourseState() {
        return this.courseState;
    }
    
    public void setCourseState(String courseState) {
        this.courseState = courseState;
    }

    
    @Column(name="state")
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="registeredCourse")
    public Set getGrades() {
        return this.grades;
    }
    
    public void setGrades(Set grades) {
        this.grades = grades;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="registeredCourse")
    public Set getUnattendances() {
        return this.unattendances;
    }
    
    public void setUnattendances(Set unattendances) {
        this.unattendances = unattendances;
    }




}


