package hibernate;
// Generated 10-06-2018 09:26:51 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Role generated by hbm2java
 */
@Entity
@XmlRootElement( name = "role")
@Table(name="role"
    ,catalog="gradecheck"
    , uniqueConstraints = @UniqueConstraint(columnNames="role") 
)
public class Role  implements java.io.Serializable {


     private Integer id;
     private String role;
     private Boolean teach;
     private Boolean manageUsers;
     private Boolean manageStudents;
     private Boolean manageEmployees;
     private Boolean manageFaculties;
     private Boolean manageCareers;
     private Boolean manageCourses;
     private Boolean managePensums;
     private Boolean manageEvaluations;
     private Boolean manageRoles;
     private Boolean state;
     @JsonBackReference
     private Set employees = new HashSet(0);

    public Role() {
    }

	
    public Role(String role) {
        this.role = role;
    }
    public Role(String role, Boolean teach, Boolean manageUsers, Boolean manageStudents, Boolean manageEmployees, Boolean manageFaculties, Boolean manageCareers, Boolean manageCourses, Boolean managePensums, Boolean manageEvaluations, Boolean manageRoles, Boolean state, Set employees) {
       this.role = role;
       this.teach = teach;
       this.manageUsers = manageUsers;
       this.manageStudents = manageStudents;
       this.manageEmployees = manageEmployees;
       this.manageFaculties = manageFaculties;
       this.manageCareers = manageCareers;
       this.manageCourses = manageCourses;
       this.managePensums = managePensums;
       this.manageEvaluations = manageEvaluations;
       this.manageRoles = manageRoles;
       this.state = state;
       this.employees = employees;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="role", unique=true, nullable=false, length=50)
    public String getRole() {
        return this.role;
    }
    
    public void setRole(String role) {
        this.role = role;
    }

    
    @Column(name="teach")
    public Boolean getTeach() {
        return this.teach;
    }
    
    public void setTeach(Boolean teach) {
        this.teach = teach;
    }

    
    @Column(name="manage_users")
    public Boolean getManageUsers() {
        return this.manageUsers;
    }
    
    public void setManageUsers(Boolean manageUsers) {
        this.manageUsers = manageUsers;
    }

    
    @Column(name="manage_students")
    public Boolean getManageStudents() {
        return this.manageStudents;
    }
    
    public void setManageStudents(Boolean manageStudents) {
        this.manageStudents = manageStudents;
    }

    
    @Column(name="manage_employees")
    public Boolean getManageEmployees() {
        return this.manageEmployees;
    }
    
    public void setManageEmployees(Boolean manageEmployees) {
        this.manageEmployees = manageEmployees;
    }

    
    @Column(name="manage_faculties")
    public Boolean getManageFaculties() {
        return this.manageFaculties;
    }
    
    public void setManageFaculties(Boolean manageFaculties) {
        this.manageFaculties = manageFaculties;
    }

    
    @Column(name="manage_careers")
    public Boolean getManageCareers() {
        return this.manageCareers;
    }
    
    public void setManageCareers(Boolean manageCareers) {
        this.manageCareers = manageCareers;
    }

    
    @Column(name="manage_courses")
    public Boolean getManageCourses() {
        return this.manageCourses;
    }
    
    public void setManageCourses(Boolean manageCourses) {
        this.manageCourses = manageCourses;
    }

    
    @Column(name="manage_pensums")
    public Boolean getManagePensums() {
        return this.managePensums;
    }
    
    public void setManagePensums(Boolean managePensums) {
        this.managePensums = managePensums;
    }

    
    @Column(name="manage_evaluations")
    public Boolean getManageEvaluations() {
        return this.manageEvaluations;
    }
    
    public void setManageEvaluations(Boolean manageEvaluations) {
        this.manageEvaluations = manageEvaluations;
    }

    
    @Column(name="manage_roles")
    public Boolean getManageRoles() {
        return this.manageRoles;
    }
    
    public void setManageRoles(Boolean manageRoles) {
        this.manageRoles = manageRoles;
    }

    
    @Column(name="state")
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="role")
    public Set getEmployees() {
        return this.employees;
    }
    
    public void setEmployees(Set employees) {
        this.employees = employees;
    }




}


