package hibernate;
// Generated 10-06-2018 09:26:51 AM by Hibernate Tools 4.3.1


import com.fasterxml.jackson.annotation.JsonBackReference;
import com.fasterxml.jackson.annotation.JsonManagedReference;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Student generated by hbm2java
 */
@Entity
@XmlRootElement(name = "student")
@Table(name="student"
    ,catalog="gradecheck"
)
public class Student  implements java.io.Serializable {


     private Integer id;
     @JsonManagedReference
     private User user;
     private Boolean state;
     @JsonBackReference
     private Set careerStudents = new HashSet(0);
     @JsonBackReference
     private Set registeredCourses = new HashSet(0);

    public Student() {
    }

	
    public Student(User user) {
        this.user = user;
    }
    public Student(User user, Boolean state, Set careerStudents, Set registeredCourses) {
       this.user = user;
       this.state = state;
       this.careerStudents = careerStudents;
       this.registeredCourses = registeredCourses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="user_id", nullable=false)
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }

    
    @Column(name="state")
    public Boolean getState() {
        return this.state;
    }
    
    public void setState(Boolean state) {
        this.state = state;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="student")
    public Set getCareerStudents() {
        return this.careerStudents;
    }
    
    public void setCareerStudents(Set careerStudents) {
        this.careerStudents = careerStudents;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="student")
    public Set getRegisteredCourses() {
        return this.registeredCourses;
    }
    
    public void setRegisteredCourses(Set registeredCourses) {
        this.registeredCourses = registeredCourses;
    }




}


